###
POST localhost:13000/accounts
Accept: application/json
Content-Type: application/json

{
  "name": "Gildong Hong",
  "password": "1234",
  "email": "water@naver.com"
}

> {%
client.global.set("id",response.body.id);
%}

###
POST localhost:13000/accounts/login
Accept: application/json
Content-Type: application/json

{
  "id": "650ced54bcf87c36db74f629",
  "password": "123"
}

###
GET localhost:13000/accounts
Accept: application/json

###
GET localhost:13000/accounts/{{id}}
Accept: application/json

###
PATCH localhost:13000/accounts/{{id}}
Accept: application/json
Content-Type: application/json

{
  "email": "123@naver.com"
}

###
DELETE localhost:13000/accounts/{{id}}
Accept: application/json

